{{- if not .Values.llm.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retail-banking-copilot.secretName" . }}
  labels:
    {{- include "retail-banking-copilot.labels" . | nindent 4 }}
type: Opaque
stringData:
  LLM_API_KEY: {{ .Values.llm.apiKey | quote }}
{{- end }}
